include:
  - ../networks.yml
x-vault-env: &vault-env
  HOMEPAGE_ALLOWED_HOSTS: ${APP_NAME}.${DOMAIN}
services:
  homepage:
    image: ghcr.io/gethomepage/homepage
    extends:
      file: ../common.yml
      service: main
    expose:
      - 3000
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=3000"
    environment: *vault-env
    volumes:
      - ../../apps-data/${APP_NAME}/config:/app/config
