# baseline fragment: dependabot
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels: []
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: daily
      time: "10:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: pre-commit
    directory: /
    labels: []
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: daily
      time: "10:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: pip
    directory: /
    labels: []
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: daily
      time: "10:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: bundler
    directory: /
    labels: []
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: daily
      time: "10:00"
      timezone: "Europe/Berlin"
# /baseline fragment: dependabot
