include:
  - ../networks.yml
services:
  databasus:
    image: databasus/databasus
    extends:
      file: ../common.yml
      service: main
    expose:
      - 4005
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=4005"
    volumes:
      - ${DATA_DIR}/data:/databasus-data
    networks:
      - internal
      - traefik
      - databases
