include:
  - ../networks.yml
x-environment: &environment
  APP_NAME: 2FAuth
  APP_ENV: local
  APP_TIMEZONE: UTC
  APP_DEBUG: false
  SITE_OWNER: ${ADMIN_MAIL}
  APP_KEY: ${KEY_HEX_16}
  APP_URL: https://${APP_NAME}.${TWOFAUTH_DOMAIN:-${DOMAIN}}
  IS_DEMO_APP: false
  LOG_CHANNEL: daily
  LOG_LEVEL: error
  DB_DATABASE: /2fauth/database.sqlite
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  MAIL_MAILER: smtp
  MAIL_HOST: ${SMTP_HOSTNAME}
  MAIL_PORT: ${SMTP_PORT}
  MAIL_USERNAME: ${SMTP_USERNAME}
  MAIL_PASSWORD: ${SMTP_PASSWORD}
  MAIL_ENCRYPTION: true
  MAIL_FROM_NAME: ${APP_NAME}
  MAIL_FROM_ADDRESS: ${SMTP_FROM}
  MAIL_VERIFY_SSL_PEER: false
  THROTTLE_API: 60
  LOGIN_THROTTLE: 5
  AUTHENTICATION_GUARD: web-guard
  AUTHENTICATION_LOG_RETENTION: 60
  WEBAUTHN_NAME: 2FAuth
  BROADCAST_DRIVER: log
  QUEUE_DRIVER: sync
  SESSION_LIFETIME: 120
  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: null
  REDIS_PORT: 6379
  MIX_ENV: local
services:
  twofauth:
    image: 2fauth/2fauth
    extends:
      file: ../common.yml
      service: main
    expose:
      - 8000
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=8000"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${TWOFAUTH_DOMAIN:-${DOMAIN}}`)"
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/2fauth:/2fauth
