include:
  - ../networks.yml
  - ../postgres-17.yml
x-environment: &environment
  GATUS_CONFIG_PATH: /config/yml
  TZ: ${TIMEZONE}
  POSTGRES_USER: ${APP_NAME}
  POSTGRES_DB: ${APP_NAME}
  POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
  TELEGRAM_ID: ${TELEGRAM_CHAT}
services:
  gatus:
    image: twinproduction/gatus
    extends:
      file: ../common.yml
      service: main
    expose:
      - 8080
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=8080"
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
      - ./config/global.yml:/config/yml/global.yml
    depends_on:
      - postgres
    healthcheck:
      disable: true
