include:
  - ../networks.yml
  - ../redis-7.yml
  - ../postgres-17.yml
  - ../timescale-17.yml
x-environment: &environment
  CODECOV_BASE_HOST: ${APP_NAME}.${DOMAIN}
  CODECOV_API_HOST: ${APP_NAME}.${DOMAIN}
  CODECOV_IA_HOST: ${APP_NAME}.${DOMAIN}
  CODECOV_SCHEME: https
  RUN_ENV: ENTERPRISE
x-volumes: &volumes
  - ./codecov.yml:/config/codecov.yml
services:
  gateway:
    image: codecov/self-hosted-gateway:latest-stable
    extends:
      file: ../common.yml
      service: main
    expose:
      - 8080
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=8080"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DOMAIN}`)"
    depends_on:
      - api
      - frontend
    volumes: *volumes
  frontend:
    image: codecov/self-hosted-frontend:latest-stable
    extends:
      file: ../common.yml
      service: side
    environment: *environment
    volumes: *volumes
    expose:
      - "8080"
  api:
    image: codecov/self-hosted-api:latest-stable
    extends:
      file: ../common.yml
      service: side
    depends_on:
      - redis
      - postgres
      - timescale
    volumes: *volumes
  worker:
    image: codecov/self-hosted-worker:latest-stable
    extends:
      file: ../common.yml
      service: side
    depends_on:
      - redis
      - postgres
      - timescale
    environment: *environment
    volumes:
      - ./codecov.yml:/config/codecov.yml
      - ../../apps-data/${APP_NAME}/archive:/archive
