include:
  - ../networks.yml
services:
  beszel:
    image: "henrygd/beszel"
    extends:
      file: ../common.yml
      service: main
    expose:
      - 8090
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=8090"
    volumes:
      - ${DATA_DIR}/beszel_data:/beszel_data
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
