include:
  - ../networks.yml
  - ../postgres-18.yml
  - ../redis-8.yml
x-image: &image glitchtip/glitchtip
x-vault-env: &vault-env
  DATABASE_URL: postgresql://${APP_NAME}:${DATABASE_PASSWORD}@postgres:5432/${APP_NAME}
  SECRET_KEY: ${SESSION_KEY}
  EMAIL_URL: ${EMAIL_URL:-consolemail://}
  GLITCHTIP_DOMAIN: https://${APP_NAME}.${DOMAIN}
  DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL:-noreply@${DOMAIN}}
x-internal-env: &internal-env
  REDIS_URL: redis://redis:6379
  PORT: 8000
  CELERY_WORKER_AUTOSCALE: "1,3"
services:
  web:
    image: *image
    extends:
      file: ../common.yml
      service: main
    expose:
      - 8000
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=8000"
    command: ["sh", "-c", "./bin/run-migrate.sh && ./bin/start.sh"]
    environment:
      <<: [*vault-env, *internal-env]
    volumes:
      - ../../apps-data/${APP_NAME}/uploads:/code/uploads
    depends_on:
      - postgres
      - redis
  worker:
    image: *image
    extends:
      file: ../common.yml
      service: side
    command: ["./bin/run-celery-with-beat.sh"]
    environment:
      <<: [*vault-env, *internal-env]
    volumes:
      - ../../apps-data/${APP_NAME}/uploads:/code/uploads
    depends_on:
      - postgres
      - redis
      - web
