# connect as user ${APP_NAME}, password ${DATABASE_PASSWORD}, database ${APP_NAME}, port 27017 (root password is also ${DATABASE_PASSWORD})
services:
  mongodb:
    image: bitnami/mongodb
    restart: unless-stopped
    environment:
      MONGODB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGODB_USERNAME: ${APP_NAME}
      MONGODB_PASSWORD: ${DATABASE_PASSWORD}
      MONGODB_DATABASE: ${APP_NAME}
    volumes:
      - ${DATA_DIR}/mongodb:/bitnami/mongodb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      internal:
      databases:
        aliases:
          - ${APP_NAME}-mongodb
