# connect as user ${APP_NAME}, password ${DATABASE_PASSWORD}, database ${APP_NAME}, port 3306 (root password is also ${DATABASE_PASSWORD})
services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${APP_NAME}
      MYSQL_USER: ${APP_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${DATA_DIR}/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      internal:
      databases:
        aliases:
          - ${APP_NAME}-mysql
