services:
  paradedb:
    image: paradedb/paradedb:latest-pg17
    restart: unless-stopped
    command: ["postgres", "-c", "log_min_messages=ERROR", "-c", "client_min_messages=ERROR"]
    # connect as user ${APP_NAME}, password ${DATABASE_PASSWORD}, database ${APP_NAME}
    environment:
      POSTGRES_DB: ${APP_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${APP_NAME}
    volumes:
      - ${DATA_DIR}/paradedb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${APP_NAME}", "-U", "${APP_NAME}"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      internal:
      databases:
        aliases:
          - ${APP_NAME}-paradedb
