# connect as user postgres, password ${DATABASE_PASSWORD}, database ${APP_NAME}, port 5432
services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    command: ["postgres", "-c", "log_min_messages=ERROR", "-c", "client_min_messages=ERROR"]
    environment:
      POSTGRES_DB: ${APP_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${DATA_DIR}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${APP_NAME}", "-U", "postgres"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      internal:
      databases:
        aliases:
          - ${APP_NAME}-postgres
