include:
  - ../networks.yml
  - ../postgres-17.yml
x-vault-env: &vault-env
  SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${ENCRYPTION_KEY}
  SEMAPHORE_DB_PASS: ${DATABASE_PASSWORD}
  SEMAPHORE_ADMIN_PASSWORD: ${ADMIN_DEFAULT_PASS}
  SEMAPHORE_ADMIN_EMAIL: ${ADMIN_MAIL}
  SEMAPHORE_TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
  SEMAPHORE_TELEGRAM_CHAT: ${TELEGRAM_CHAT}
x-internal-env: &internal-env
  SEMAPHORE_DB_DIALECT: postgres
  SEMAPHORE_DB_HOST: postgres
  SEMAPHORE_DB_NAME: ${APP_NAME}
  SEMAPHORE_DB_USER: postgres
  SEMAPHORE_ADMIN: admin
  SEMAPHORE_ADMIN_NAME: admin
  SEMAPHORE_TELEGRAM_ALERT: true
  ANSIBLE_HOST_KEY_CHECKING: false
services:
  semaphore:
    image: semaphoreui/semaphore
    extends:
      file: ../common.yml
      service: main
    expose:
      - 3000
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=3000"
    environment:
      <<: [*vault-env, *internal-env]
    depends_on:
      - postgres
