name: Deploy
on:
  workflow_dispatch:
    inputs:
      target:
        description: Deploy target to redeploy.
        type: string
        required: true
jobs:
  deploy-targets:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.load-targets.outputs.matrix }}
      count: ${{ steps.load-targets.outputs.count }}
    steps:
      - uses: actions/checkout@v7
      - uses: $/.github/actions/load-yaml-matrix
        id: load-targets
        with:
          directory: targets
          name: ${{ inputs.target }}
  deploy:
    needs: deploy-targets
    if: needs.deploy-targets.outputs.count != '0'
    strategy:
      matrix: ${{ fromJson(needs.deploy-targets.outputs.matrix) }}
    uses: $/.github/workflows/deploy-shared.yml
    with:
      target-manifest: ${{ matrix.manifest }}
      tailscale-oauth-client-id: ${{ vars[matrix.credentials.variables.tailscale_oauth_client_id] }}
    secrets:
      ssh-private-key: ${{ secrets[matrix.credentials.secrets.ssh_private_key] }}
      tailscale-oauth-secret: ${{ secrets[matrix.credentials.secrets.tailscale_oauth_secret] }}
      sops-age-key: ${{ secrets[matrix.credentials.secrets.sops_age_key] }}
