name: Lint
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  lint:
    uses: rubykatzen/baseline/.github/workflows/lint-shared.yml@v0.12
    with:
      linters: yamllint, pymarkdown, ruff, shellcheck, actionlint, pre-commit
