name: Notify Telegram release
on:
  release:
    types: [published]
jobs:
  notify:
    if: >-
      github.event_name == 'release' &&
      github.event.action == 'published'
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - id: prepare
        uses: rubykatzen/baseline/.github/actions/prepare-telegram-release-message@v0.16.2
      - name: Send
        uses: rubykatzen/baseline/.github/actions/send-telegram-message@v0.16.2
        with:
          message: ${{ steps.prepare.outputs.message }}
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-chat-id: ${{ vars.TELEGRAM_CHAT_ID }}
          parse-mode: MarkdownV2
