asset: hawkeye-traefik.sops.env
keys:
  - hawkeye
env:
  ADMIN_MAIL: ADMIN_MAIL
  DNS_CHALLENGE_PROVIDER: DNS_CHALLENGE_PROVIDER
  DNS_CHALLENGE_TOKEN: DNS_CHALLENGE_TOKEN
  HTTP_PORT: TRAEFIK_HTTP_PORT
  HTTPS_PORT: TRAEFIK_HTTPS_PORT
