asset: hawkeye-traefik.sops.env
keys:
  - hawkeye
env:
  APPS_ADMIN_MAIL: RUBYKATZEN_COM_ADMIN_MAIL
  APPS_CLOUDFLARE_DNS_API_TOKEN: RUBYKATZEN_COM_CLOUDFLARE_TOKEN
  HTTP_PORT: RUBYKATZEN_COM_TRAEFIK_HTTP_PORT
  HTTPS_PORT: RUBYKATZEN_COM_TRAEFIK_HTTPS_PORT
