asset: traefik.sops.env
keys:
  - heimdall
env:
  ADMIN_MAIL: ADMIN_MAIL
  DNS_CHALLENGE_PROVIDER: DNS_CHALLENGE_PROVIDER
  DNS_CHALLENGE_TOKEN: CLOUDFLARE_DNS_API_TOKEN
  HTTP_PORT: TRAEFIK_HTTP_PORT
  HTTPS_PORT: TRAEFIK_HTTPS_PORT
